site_name: 3XAY
dev_addr: localhost:33333
site_author: Ayan Bindal (3XAY)

nav:
    - Home: index.md
    - My Work: work.md
    - Contact: contact.md
  
theme:
    name: material
    locale: en_US
    logo: assets/Logo.gif
    favicon: assets/Logo.png

plugins:
    - search:
    - open-in-new-tab:
    - spellcheck: #Run the following in the console: mkdocs build -s
        min_length: 2
        max_capital: 1
        known_words: knownWords.txt


extra_css:
    - stylesheets/style.css
    - stylesheets/simple-styles.css
    - stylesheets/simple-theme.css

#Add JS with:
#extra_javascript:
#   - jsFile.js