site_name: 3XAY
dev_addr: localhost:33333
site_author: Ayan Bindal (3XAY)

nav:
    - Home: index.md
    - My Work: work.md
    - Contact: contact.md
  
theme:
    name: material
    logo: assets/Logo.gif
    favicon: assets/Logo.png
    palette:
        scheme: slate
        primary: black
        accent: amber
    font:
        text: Fira Mono
        code: Cascadia Code
    language: en
    features:
        - navigation.instant.progress
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.prune
        - navigation.indexes
        - toc.follow
        - navigation.top
        - search.suggest


plugins:
    - search:
    - open-in-new-tab:
    - spellcheck: #Run the following in the console: mkdocs build -s
        min_length: 2
        max_capital: 1
        known_words: knownWords.txt


extra_css:
    - stylesheets/style.css
    - stylesheets/extra.css
    - stylesheets/theme.css

#Add JS with:
#extra_javascript:
#   - jsFile.js