site_name: 3XAY
dev_addr: localhost:33333
site_author: Ayan Bindal (3XAY)

nav:
    - Home: index.md
    - My Work: work.md
    - Contact: contact.md
  
theme:
    name: simple-blog
    locale: en
    theme_style: dark
    logo: assets/Logo.gif
    favicon: assets/Logo.png
    components:
        site_name: true
        title: false
        menu: true
        preview: false
        footer: false

plugins:
    - open-in-new-tab:
    - spellcheck:
        min_length: 2
        max_capital: 1
        known_words: knownWords.txt


extra_css:
    - style.css

#Add JS with:
#extra_javascript:
#   - jsFile.js